### ISSUE TITLE
Error "IndexError: list index out of range" while testing

### ISSUE THREAD

**Issue by FiReTiTi** [proton-bit/Blur_Artifacts_Detection#2]
Hi,
I tried to use the YOLO version on some images, but I got the following error:

    [~/Downloads/CycIF/Phenocycler/Blur Detection/Blur_Artifacts_Detection/yolo] ᐅ python yolov7/detect.py --weights best.pt --conf 0.001 --img-size 1280 --iou-thres 0.25 --source /Users/XXX/Downloads/CycIF/Phenocycler/4-24AP/CodexFixer_Results/4-24AP-Crop3-RGB.tif
    Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.001, device='', exist_ok=False, img_size=1280, iou_thres=0.25, name='exp', no_trace=False, nosave=False, project='runs/detect', save_conf=False, save_txt=False, source='/Users/XXX/Downloads/CycIF/Phenocycler/4-24AP/CodexFixer_Results/4-24AP-Crop3-RGB.tif', update=False, view_img=False, weights=['best.pt'])
    YOLOR 🚀 2024-5-21 torch 2.2.2 CPU
    
    Traceback (most recent call last):
      File "/Users/XXX/Downloads/CycIF/Phenocycler/Blur Detection/Blur_Artifacts_Detection/yolo/yolov7/utils/google_utils.py", line 26, in attempt_download
        assets = [x['name'] for x in response['assets']]  # release assets
    KeyError: 'assets'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "yolov7/detect.py", line 196, in <module>
        detect()
      File "yolov7/detect.py", line 34, in detect
        model = attempt_load(weights, map_location=device)  # load FP32 model
      File "/Users/XXX/Downloads/CycIF/Phenocycler/Blur Detection/Blur_Artifacts_Detection/yolo/yolov7/models/experimental.py", line 251, in attempt_load
        attempt_download(w)
      File "/Users/XXX/Downloads/CycIF/Phenocycler/Blur Detection/Blur_Artifacts_Detection/yolo/yolov7/utils/google_utils.py", line 31, in attempt_download
        tag = subprocess.check_output('git tag', shell=True).decode().split()[-1]
    IndexError: list index out of range

As it can be observed in the command line, I simply tried to process a single image.

**Comment by unsaid-azizov** [comment]
Sorry, this repository is no longer maintained and will be archived soon.
